languageCode = "en"
languageName = "English"
weight = 1
title = "phish"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "PATH"
  # secondaryLogo = "PATH"
  description = "personal blog site"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Daniel Underhay"
  image = "img/me.jpeg"
  headline = "personal blog site"
  bio = "👋"
  links = [
     { github = "https://github.com/dunderhay/" },
     { linkedin = "https://au.linkedin.com/in/daniel-underhay" },
     { twitter = "https://twitter.com/dunderhay" },
  ]
