title: "Phish's Blog"
author: "🐟"
description: "A spot for me to write about stuff and things"

# Jekyll settings
permalink: /:categories/:year/:month/:day/:title          # see https://jekyllrb.com/docs/permalinks/
paginate: 4                  # number of articles per page, remove to disable pagination
# excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: true         # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
style: default               # choose between "default", "contrast" and "minimal"
dark_theme: true             # enables dark mode

navigation:                  # (optional) site navigation in the header
  - index.html

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  github: "https://github.com/dunderhay"

plugins:
 - jekyll-paginate
 - jekyll-default-layout
 - jekyll-remote-theme

remote_theme: dunderhay/contrast
