title: "Phish's Blog"
author: "🐟"
description: "A spot for me to write about stuff and things"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: true
minimal: false

# Menu

navigation:
  - {file: "index.html", icon: home}

external:
  - {title: Github, icon: github, url: "https://github.com/dunderhay"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/dunderhay"}

# Theme
remote_theme: dunderhay/contrast@2.6

plugins:
  - jekyll-remote-theme